// server/controllers/exportController.js
// Generates and streams PDF and CSV expense reports

const PDFDocument = require("pdfkit");
const { Parser }  = require("json2csv");
const Expense     = require("../models/Expense");

// ─── Helper: build query from filters ────────────────────────────────────────
const buildQuery = (userId, query) => {
  const q = { user: userId };

  if (query.category)  q.category = query.category;
  if (query.startDate || query.endDate) {
    q.date = {};
    if (query.startDate) q.date.$gte = new Date(query.startDate);
    if (query.endDate)   q.date.$lte = new Date(query.endDate);
  }

  return q;
};

// ─── GET /api/export/pdf ──────────────────────────────────────────────────────
const exportPDF = async (req, res, next) => {
  try {
    const query    = buildQuery(req.user._id, req.query);
    const expenses = await Expense.find(query).sort({ date: -1 });

    // Set response headers for file download
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="expenses-${Date.now()}.pdf"`
    );

    // Create PDF document and pipe to response
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    doc.pipe(res);

    // ── Header ──
    doc
      .fontSize(22)
      .fillColor("#2563eb")
      .text("ExpenseIQ — Expense Report", { align: "center" });

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text(
        `Generated: ${new Date().toLocaleDateString()} · User: ${req.user.name}`,
        { align: "center" }
      );

    doc.moveDown(1);

    // ── Summary ──
    const total = expenses.reduce((sum, e) => sum + e.amount, 0);

    doc
      .fontSize(12)
      .fillColor("#111827")
      .text(`Total expenses: ${expenses.length}`)
      .text(`Total amount:   $${total.toFixed(2)}`)
      .moveDown(1);

    // ── Table header ──
    const colX = { date: 40, title: 120, category: 270, method: 380, amount: 490 };

    doc
      .fontSize(10)
      .fillColor("#ffffff")
      .rect(40, doc.y, 520, 20)
      .fill("#2563eb");

    const headerY = doc.y - 15;
    doc.fillColor("#ffffff");
    doc.text("Date",     colX.date,     headerY);
    doc.text("Title",    colX.title,    headerY);
    doc.text("Category", colX.category, headerY);
    doc.text("Method",   colX.method,   headerY);
    doc.text("Amount",   colX.amount,   headerY);

    doc.moveDown(0.5);

    // ── Table rows ──
    expenses.forEach((exp, i) => {
      // Alternate row background
      if (i % 2 === 0) {
        doc.rect(40, doc.y - 3, 520, 18).fill("#f3f4f6");
      }

      doc.fillColor("#111827").fontSize(9);

      const rowY = doc.y - 3;
      doc.text(new Date(exp.date).toLocaleDateString(), colX.date,     rowY, { width: 75 });
      doc.text(exp.title,                               colX.title,    rowY, { width: 145 });
      doc.text(exp.category,                            colX.category, rowY, { width: 105 });
      doc.text(exp.paymentMethod,                       colX.method,   rowY, { width: 100 });
      doc.text(`$${exp.amount.toFixed(2)}`,             colX.amount,   rowY, { width: 70 });

      doc.moveDown(0.6);

      // New page if needed
      if (doc.y > 750) doc.addPage();
    });

    // ── Footer ──
    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("#9ca3af")
      .text("Generated by ExpenseIQ · Smart Expense Tracking", {
        align: "center",
      });

    doc.end();
  } catch (error) {
    next(error);
  }
};

// ─── GET /api/export/csv ──────────────────────────────────────────────────────
const exportCSV = async (req, res, next) => {
  try {
    const query    = buildQuery(req.user._id, req.query);
    const expenses = await Expense.find(query).sort({ date: -1 });

    // Shape data for CSV
    const data = expenses.map((e) => ({
      Date:            new Date(e.date).toLocaleDateString(),
      Title:           e.title,
      Amount:          e.amount.toFixed(2),
      Category:        e.category,
      "Payment Method": e.paymentMethod,
      Description:     e.description || "",
      Recurring:       e.isRecurring ? "Yes" : "No",
      Frequency:       e.recurringFrequency || "",
    }));

    const parser = new Parser({
      fields: [
        "Date", "Title", "Amount", "Category",
        "Payment Method", "Description", "Recurring", "Frequency",
      ],
    });

    const csv = parser.parse(data);

    res.setHeader("Content-Type", "text/csv");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="expenses-${Date.now()}.csv"`
    );

    res.send(csv);
  } catch (error) {
    next(error);
  }
};

module.exports = { exportPDF, exportCSV };